name: Oppiabot

on:
  issues:
    types:
      - labeled


jobs:
  oppiabot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/oppiabot/
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
