name: Oppiabot

on:
  issues:
    types:
      - labeled
      - assigned

jobs:
  oppiabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JamesOppiabot
        uses: jameesjohn/oppia-actions@0.2.3
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          google-api-key: ${{secrets.GOOGLE_API_KEY}}
          cla-sheet-id: ${{secrets.CLA_SHEET_ID}}
