name: Oppiabot

on:
  issues:
    types:
      - labeled

jobs:
  oppiabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JamesOppiabot
        uses: jameesjohn/oppia-actions@0.1.1
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
