name: First workflow for this repo

on: pull_request

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JamesOppiabot
        uses: jameesjohn/oppia-actions@0.1.0
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
