name: Oppiabot

on:
  issues:
    types:
      - labeled
      - assigned

jobs:
  oppiabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JamesOppiabot
        uses: jameesjohn/oppia-actions@0.1.9
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          google-client-credentials: ${{secrets.GOOGLE_CLIENT_CREDENTIALS}}
          google-auth-credentials: ${{secrets.GOOGLE_AUTH_CREDENTIALS}}
          cla-sheet-id: ${{secrets.CLA_SHEET_ID}}
